
package calculator;

/**
 *
 * @author DELL
 */
public class Calci extends javax.swing.JFrame {
    
    boolean decimalClick = true;
    boolean zeroClick = false;
    double a;
    double b;
    double c;
    double temp = 0.0,temp3 =1.0;
  int   plusCount = -1;
    boolean plusClick = true;
    boolean minusClick = false;
    boolean divideClick = false;
    boolean multiplyClick = false;
    boolean powerClick = false;
    boolean modulasClick = false;  
    boolean oneClick = true;
    boolean twoClick = true;
    boolean threeClick = true;
    boolean fourClick = true;
    boolean fiveClick = true;
    boolean sixClick = true;
    boolean sevenClick = true;
    boolean eightClick = true;
    boolean nineClick = true;
    boolean displayClick = false;
    boolean avalue = true;
   
    
    


       public Calci() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        eight = new javax.swing.JButton();
        seven = new javax.swing.JButton();
        plus = new javax.swing.JButton();
        nine = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        five = new javax.swing.JButton();
        six = new javax.swing.JButton();
        minus = new javax.swing.JButton();
        four = new javax.swing.JButton();
        multiply = new javax.swing.JButton();
        one = new javax.swing.JButton();
        three = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        decimal = new javax.swing.JButton();
        two = new javax.swing.JButton();
        devide = new javax.swing.JButton();
        plusMinus = new javax.swing.JButton();
        zero = new javax.swing.JButton();
        equal = new javax.swing.JButton();
        display = new javax.swing.JTextField();
        sin = new javax.swing.JButton();
        cos = new javax.swing.JButton();
        tan = new javax.swing.JButton();
        e = new javax.swing.JButton();
        log = new javax.swing.JButton();
        scientific = new javax.swing.JRadioButton();
        modulass = new javax.swing.JButton();
        log2 = new javax.swing.JButton();
        square = new javax.swing.JButton();
        sqrt = new javax.swing.JButton();
        cube = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        temp1 = new javax.swing.JButton();
        temp2 = new javax.swing.JButton();
        back = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(0, 255, 102));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));

        eight.setBackground(new java.awt.Color(51, 0, 51));
        eight.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        eight.setForeground(new java.awt.Color(240, 240, 240));
        eight.setText("8");
        eight.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 255, 255), null));
        eight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eightActionPerformed(evt);
            }
        });

        seven.setBackground(new java.awt.Color(51, 0, 51));
        seven.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        seven.setForeground(new java.awt.Color(240, 240, 240));
        seven.setText("7");
        seven.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 255, 255), null));
        seven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sevenActionPerformed(evt);
            }
        });

        plus.setBackground(new java.awt.Color(51, 0, 51));
        plus.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        plus.setForeground(new java.awt.Color(240, 240, 240));
        plus.setText("+");
        plus.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 255, 255), null));
        plus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plusActionPerformed(evt);
            }
        });

        nine.setBackground(new java.awt.Color(51, 0, 51));
        nine.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        nine.setForeground(new java.awt.Color(240, 240, 240));
        nine.setText("9");
        nine.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 255, 255), null));
        nine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nineActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(51, 0, 51));
        jButton5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton5.setForeground(new java.awt.Color(240, 240, 240));
        jButton5.setText("1");
        jButton5.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 255, 255), null));

        five.setBackground(new java.awt.Color(51, 0, 51));
        five.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        five.setForeground(new java.awt.Color(240, 240, 240));
        five.setText("5");
        five.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 255, 255), null));
        five.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fiveActionPerformed(evt);
            }
        });

        six.setBackground(new java.awt.Color(51, 0, 51));
        six.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        six.setForeground(new java.awt.Color(240, 240, 240));
        six.setText("6");
        six.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 255, 255), null));
        six.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sixActionPerformed(evt);
            }
        });

        minus.setBackground(new java.awt.Color(51, 0, 51));
        minus.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        minus.setForeground(new java.awt.Color(240, 240, 240));
        minus.setText("-");
        minus.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 255, 255), null));
        minus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minusActionPerformed(evt);
            }
        });

        four.setBackground(new java.awt.Color(51, 0, 51));
        four.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        four.setForeground(new java.awt.Color(240, 240, 240));
        four.setText("4");
        four.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 255, 255), null));
        four.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fourActionPerformed(evt);
            }
        });

        multiply.setBackground(new java.awt.Color(51, 0, 51));
        multiply.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        multiply.setForeground(new java.awt.Color(240, 240, 240));
        multiply.setText("*");
        multiply.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 255, 255), null));
        multiply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multiplyActionPerformed(evt);
            }
        });

        one.setBackground(new java.awt.Color(51, 0, 51));
        one.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        one.setForeground(new java.awt.Color(240, 240, 240));
        one.setText("1");
        one.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 255, 255), null));
        one.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oneActionPerformed(evt);
            }
        });

        three.setBackground(new java.awt.Color(51, 0, 51));
        three.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        three.setForeground(new java.awt.Color(240, 240, 240));
        three.setText("3");
        three.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 255, 255), null));
        three.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                threeActionPerformed(evt);
            }
        });

        clear.setBackground(new java.awt.Color(51, 0, 51));
        clear.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        clear.setForeground(new java.awt.Color(240, 240, 240));
        clear.setText("C");
        clear.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 255, 255), null));
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });

        decimal.setBackground(new java.awt.Color(51, 0, 51));
        decimal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        decimal.setForeground(new java.awt.Color(240, 240, 240));
        decimal.setText(".");
        decimal.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 255, 255), null));
        decimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decimalActionPerformed(evt);
            }
        });

        two.setBackground(new java.awt.Color(51, 0, 51));
        two.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        two.setForeground(new java.awt.Color(240, 240, 240));
        two.setText("2");
        two.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 255, 255), null));
        two.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twoActionPerformed(evt);
            }
        });

        devide.setBackground(new java.awt.Color(51, 0, 51));
        devide.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        devide.setForeground(new java.awt.Color(240, 240, 240));
        devide.setText("/");
        devide.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 255, 255), null));
        devide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                devideActionPerformed(evt);
            }
        });

        plusMinus.setBackground(new java.awt.Color(51, 0, 51));
        plusMinus.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        plusMinus.setForeground(new java.awt.Color(240, 240, 240));
        plusMinus.setText("+/-");
        plusMinus.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 255, 255), null));
        plusMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plusMinusActionPerformed(evt);
            }
        });

        zero.setBackground(new java.awt.Color(51, 0, 51));
        zero.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        zero.setForeground(new java.awt.Color(240, 240, 240));
        zero.setText("0");
        zero.setBorder(null);
        zero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zeroActionPerformed(evt);
            }
        });

        equal.setBackground(new java.awt.Color(51, 0, 51));
        equal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        equal.setForeground(new java.awt.Color(240, 240, 240));
        equal.setText("=");
        equal.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 255, 255), null));
        equal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equalActionPerformed(evt);
            }
        });

        display.setBackground(new java.awt.Color(0, 0, 0));
        display.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        display.setForeground(new java.awt.Color(255, 255, 255));
        display.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        display.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        display.setEnabled(false);
        display.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayActionPerformed(evt);
            }
        });

        sin.setBackground(new java.awt.Color(51, 0, 51));
        sin.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        sin.setForeground(new java.awt.Color(240, 240, 240));
        sin.setText("sin");
        sin.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 255, 255), null));
        sin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sinActionPerformed(evt);
            }
        });

        cos.setBackground(new java.awt.Color(51, 0, 51));
        cos.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cos.setForeground(new java.awt.Color(240, 240, 240));
        cos.setText("cos");
        cos.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 255, 255), null));
        cos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cosActionPerformed(evt);
            }
        });

        tan.setBackground(new java.awt.Color(51, 0, 51));
        tan.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tan.setForeground(new java.awt.Color(240, 240, 240));
        tan.setText("tan");
        tan.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 255, 255), null));
        tan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tanActionPerformed(evt);
            }
        });

        e.setBackground(new java.awt.Color(51, 0, 51));
        e.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        e.setForeground(new java.awt.Color(240, 240, 240));
        e.setText("Exp");
        e.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 255, 255), null));
        e.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eActionPerformed(evt);
            }
        });

        log.setBackground(new java.awt.Color(51, 0, 51));
        log.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        log.setForeground(new java.awt.Color(240, 240, 240));
        log.setText("Log");
        log.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 255, 255), null));
        log.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logActionPerformed(evt);
            }
        });

        scientific.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        scientific.setForeground(new java.awt.Color(255, 255, 255));
        scientific.setSelected(true);
        scientific.setText("Scientific");
        scientific.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scientificActionPerformed(evt);
            }
        });

        modulass.setBackground(new java.awt.Color(51, 0, 51));
        modulass.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        modulass.setForeground(new java.awt.Color(240, 240, 240));
        modulass.setText("%");
        modulass.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 255, 255), null));
        modulass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modulassActionPerformed(evt);
            }
        });

        log2.setBackground(new java.awt.Color(51, 0, 51));
        log2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        log2.setForeground(new java.awt.Color(240, 240, 240));
        log2.setText("x^4");
        log2.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 255, 255), null));
        log2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                log2ActionPerformed(evt);
            }
        });

        square.setBackground(new java.awt.Color(51, 0, 51));
        square.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        square.setForeground(new java.awt.Color(240, 240, 240));
        square.setText("x^2");
        square.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 255, 255), null));
        square.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                squareActionPerformed(evt);
            }
        });

        sqrt.setBackground(new java.awt.Color(51, 0, 51));
        sqrt.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        sqrt.setForeground(new java.awt.Color(240, 240, 240));
        sqrt.setText("sqrt");
        sqrt.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 255, 255), null));
        sqrt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sqrtActionPerformed(evt);
            }
        });

        cube.setBackground(new java.awt.Color(51, 0, 51));
        cube.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cube.setForeground(new java.awt.Color(240, 240, 240));
        cube.setText("x^3");
        cube.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 255, 255), null));
        cube.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cubeActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(0, 153, 153));
        jPanel4.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 153, 153)));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 13, Short.MAX_VALUE)
        );

        temp1.setBackground(new java.awt.Color(51, 0, 51));
        temp1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        temp1.setForeground(new java.awt.Color(240, 240, 240));
        temp1.setText("C-F");
        temp1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 255, 255), null));
        temp1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                temp1ActionPerformed(evt);
            }
        });

        temp2.setBackground(new java.awt.Color(51, 0, 51));
        temp2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        temp2.setForeground(new java.awt.Color(240, 240, 240));
        temp2.setText("F-C");
        temp2.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 255, 255), null));
        temp2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                temp2ActionPerformed(evt);
            }
        });

        back.setBackground(new java.awt.Color(51, 0, 51));
        back.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        back.setForeground(new java.awt.Color(240, 240, 240));
        back.setText("back");
        back.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 255, 255), null));
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(nine, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(six, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(three, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(clear, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(five, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(eight, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(two, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(zero, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(plusMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(four, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(seven, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(one, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(decimal, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(multiply, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(cos, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(devide, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(tan, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(minus, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(sin, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(plus, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(log, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(15, 15, 15)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(square, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cube, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(log2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(sqrt, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(temp1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(temp2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(e, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(modulass, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(equal, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(scientific)
                    .addComponent(display))
                .addContainerGap(21, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(34, 34, 34)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(347, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(display, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(scientific)
                        .addGap(12, 29, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(back, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(temp2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(temp1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eight, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seven, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(plus, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nine, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(log, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sqrt, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(five, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(six, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(four, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(minus, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sin, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(square, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(three, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(two, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(one, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(multiply, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cos, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cube, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(clear, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(zero, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(decimal, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(devide, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(log2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(plusMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(e, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(modulass, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(equal, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(196, 196, 196)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(317, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void eightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eightActionPerformed
        // TODO add your handling code here:
        if(eightClick){
         display.setText(display.getText() +  eight.getText());
          zeroClick = true;
          displayClick = true;
        }
    }//GEN-LAST:event_eightActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
                display.setText("");
                decimalClick =  true;
                zeroClick = false;
                plusClick = false;
                oneClick = true;
      
             twoClick = true;
                threeClick = true;
                fourClick = true;
                fiveClick = true;
                sixClick = true;
                sevenClick = true;
                eightClick = true;
                nineClick = true;
                displayClick = false;
                
    }//GEN-LAST:event_clearActionPerformed

    private void oneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oneActionPerformed
            if(oneClick){
            display.setText(display.getText() +  one.getText());
           
              zeroClick = true;
              displayClick = true; 
               
            }
    }//GEN-LAST:event_oneActionPerformed

    private void twoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twoActionPerformed
        // TODO add your handling code here:
        if(twoClick){
         display.setText(display.getText() +  two.getText());
          zeroClick = true;
          displayClick = true;
           
        }
    }//GEN-LAST:event_twoActionPerformed

    private void threeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_threeActionPerformed
        // TODO add your handling code here:  
        if(threeClick){
        display.setText(display.getText() +  three.getText());
        zeroClick = true;
        displayClick = true;
         
        }
    }//GEN-LAST:event_threeActionPerformed

    private void fourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fourActionPerformed
        
        if(fourClick){
          
        
         display.setText(display.getText() +  four.getText());
         zeroClick = true;
         displayClick = true;
         
        }
    }//GEN-LAST:event_fourActionPerformed

    private void fiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fiveActionPerformed
        // TODO add your handling code here:
        if(fiveClick){
            
        
         display.setText(display.getText() +  five.getText());
         zeroClick = true;
         displayClick = true;
         
        }
    }//GEN-LAST:event_fiveActionPerformed

    private void sixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sixActionPerformed
        // TODO add your handling code here:
        if(sixClick){ 
        display.setText(display.getText() +  six.getText());
         zeroClick = true;
         displayClick = true;
          
                   
        }
    }//GEN-LAST:event_sixActionPerformed

    private void sevenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sevenActionPerformed
        if(sevenClick){
         display.setText(display.getText() +  seven.getText());
         zeroClick = true;
          displayClick = true;
        }
        
    }//GEN-LAST:event_sevenActionPerformed

    private void nineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nineActionPerformed
        // TODO add your handling code here:
        if(nineClick){
        display.setText(display.getText() + nine.getText());
        zeroClick = true;
        displayClick = true;
        }        
    }//GEN-LAST:event_nineActionPerformed

    private void zeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zeroActionPerformed
        if(zeroClick)
        display.setText(display.getText() +  zero.getText());
    }//GEN-LAST:event_zeroActionPerformed

    private void decimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decimalActionPerformed
       
        if(decimalClick){
            
                   if(display.getText().equals(""))
                   {
                       display.setText("0.");
                       decimalClick = false;
                   }else{
                    display.setText(display.getText() +  decimal.getText());
                    decimalClick = false;
        }
        }
    }//GEN-LAST:event_decimalActionPerformed

    private void plusMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plusMinusActionPerformed
        
        double value = Double.parseDouble(display.getText());
        value = value * -1 ;
        if(decimalClick){
                 display.setText(String.valueOf((int)value));
        }
        else{
            display.setText(String.valueOf( value));
        }
    }//GEN-LAST:event_plusMinusActionPerformed

    private void plusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plusActionPerformed
                 
               if(displayClick){
                       a = Double.parseDouble(display.getText());
                        temp = temp + a ;
                        a = temp;
                        display.setText("");
                        avalue = decimalClick;
                        plusClick = true;
                        minusClick =false;
                        divideClick = false;
                        multiplyClick = false;
                        decimalClick = true;
                        oneClick = true;
                        twoClick = true;
                        threeClick = true;
                        fourClick = true;
                        fiveClick = true;
                        sixClick = true;
                        sevenClick = true;
                        eightClick = true;
                        nineClick = true;
               }else{
                   display.setText("Please Enter a Number First..!");
               }
          
    }//GEN-LAST:event_plusActionPerformed

    private void displayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_displayActionPerformed

    private void sinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sinActionPerformed
             
          if(!display.getText().isEmpty()) {    
         display.setText( String.valueOf(Math.sin(Double.parseDouble(display.getText()))));
          decimalClick = false;
          }

        
    }//GEN-LAST:event_sinActionPerformed

    private void cosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cosActionPerformed
        // TODO add your handling code here:
        if(!display.getText().isEmpty()){
        display.setText(String.valueOf(Math.cos(Double.parseDouble(display.getText()))));
        decimalClick = false;
        }
        
    }//GEN-LAST:event_cosActionPerformed

    private void tanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tanActionPerformed
        if(!display.getText().isEmpty()){
        display.setText(String.valueOf(Math.tan(Double.parseDouble(display.getText()))));
         decimalClick = false;
        }
    }//GEN-LAST:event_tanActionPerformed

    private void eActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eActionPerformed
        if(!display.getText().isEmpty()){
        display.setText(String.valueOf(Math.getExponent(Double.parseDouble(display.getText()))));
         decimalClick = false;
        }

    }//GEN-LAST:event_eActionPerformed

    private void logActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logActionPerformed
         if(!display.getText().isEmpty())
          {
        display.setText(String.valueOf(Math.log(Double.parseDouble(display.getText()))));
              decimalClick = false;
        }
    }//GEN-LAST:event_logActionPerformed

    private void minusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minusActionPerformed
        
               if(displayClick){
                a = Double.parseDouble(display.getText());
                           
                
                display.setText("");
                avalue = decimalClick;
                decimalClick = true;
                plusClick = false;
                minusClick =true;
                divideClick = false;
                multiplyClick = false;
                oneClick = true;
                twoClick = true;
                threeClick = true;
                fourClick = true;
                fiveClick = true;
                sixClick = true;
                sevenClick = true;
                eightClick = true;
                nineClick = true;
               }
               else{
                   display.setText("Please Enter a Number First..!");
               }
                
    }//GEN-LAST:event_minusActionPerformed

    private void multiplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multiplyActionPerformed
         
             if(displayClick){
               a = Double.parseDouble(display.getText());
               temp3 = temp3 * a ;
               a = temp3;
                display.setText("");
                 avalue = decimalClick;
                decimalClick = true;
                plusClick = false;
                minusClick =false;
                divideClick = false;
                multiplyClick = true;
                
                oneClick = true;
                twoClick = true;
                threeClick = true;
                fourClick = true;
                fiveClick = true;
                sixClick = true;
                sevenClick = true;
                eightClick = true;
                nineClick = true;
             }
             else{
                   display.setText("Please Enter a Number First..!");
               }
    }//GEN-LAST:event_multiplyActionPerformed

    private void devideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_devideActionPerformed
              if(displayClick){ 
              a = Double.parseDouble(display.getText());
                display.setText("");
                avalue = decimalClick;
                decimalClick = true;
                plusClick = false;
                minusClick =false;
                divideClick =  true;
                multiplyClick = false;
                
                oneClick = true;
                twoClick = true;
                threeClick = true;
                fourClick = true;
                fiveClick = true;
                sixClick = true;
                sevenClick = true;
                eightClick = true;      
                nineClick = true;
              }
              else{
                   display.setText("Please Enter a Number First..!");
               }
    }//GEN-LAST:event_devideActionPerformed

    private void equalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equalActionPerformed
  
                    temp3= 1.0;
                     temp = 0.0;            
                 if(plusClick){
                        b = Double.parseDouble(display.getText());
                        c = a+b;
                         if(decimalClick && avalue){
                              display.setText(String.valueOf((int)c));
                         }
                         else{
                                
                                  display.setText(String.valueOf((double)c));
                                  plusClick = false;
                                 decimalClick = false;
                         }
                 }
                 
                 else if(minusClick){
                      b = Double.parseDouble(display.getText());
                           c = a-b;
                            if(decimalClick && avalue){
                              display.setText(String.valueOf((int)c));
                         }
                         else{
                                
                                  display.setText(String.valueOf(c));
                                  minusClick = false;
                                 decimalClick = false;
                         }
                 }
                 else if(multiplyClick){
                      b = Double.parseDouble(display.getText());
                          c = a*b;
                          if(decimalClick && avalue){
                              display.setText(String.valueOf((int)c));
                         }
                         else{
                                
                                  display.setText(String.valueOf(c));
                                  multiplyClick = false;
                                 decimalClick = false;
                         }
                 }
                 else if(divideClick){ 
                     b = Double.parseDouble(display.getText());
                          
                         if(b == 0.0){
                             display.setText("Please don't divide by 0");
                         }else{
                            c = a/b;
                    
                           display.setText(String.valueOf(c));
                           divideClick = false;
                           decimalClick = false;
                         }
                 }  else if(modulasClick){
                     b = Double.parseDouble(display.getText());
                     c = (a*b)/100;
                      display.setText(String.valueOf(c));
               
             
             oneClick =false;
           
                twoClick = false;
                threeClick = false;
                fourClick = false;
                fiveClick = false;
                sixClick = false;
                sevenClick = false;
                eightClick = false;
                nineClick = false;
                decimalClick = true;
                 }
                
             
    }//GEN-LAST:event_equalActionPerformed

    private void scientificActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scientificActionPerformed
          
    }//GEN-LAST:event_scientificActionPerformed

    private void modulassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modulassActionPerformed
      
               a = Double.parseDouble(display.getText());
               display.setText("");
                                
                plusClick = false;
                minusClick =false;
                divideClick = false;
                multiplyClick = false;
                        
                modulasClick = true;
          
    }//GEN-LAST:event_modulassActionPerformed

    private void log2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_log2ActionPerformed
        // TODO add your handling code here:
         if(decimalClick){
          display.setText(String.valueOf((int)(Math.pow(Integer.parseInt(display.getText()), 4   ))));
            }else{
                 display.setText(String.valueOf(Math.pow(Double.parseDouble(display.getText()), 4 )));
            }
    }//GEN-LAST:event_log2ActionPerformed

    private void squareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_squareActionPerformed
         
         
          
          if(decimalClick){
          display.setText(String.valueOf((int)(Math.pow(Integer.parseInt(display.getText()), 2    ))));
            }else{
                 display.setText(String.valueOf(Math.pow(Double.parseDouble(display.getText()), 2 )));
            }
    }//GEN-LAST:event_squareActionPerformed

    private void sqrtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sqrtActionPerformed
              
                
               display.setText(String.valueOf(Math.sqrt(Integer.parseInt(display.getText()))));
               
               
               
              /*   if(decimalClick){
          display.setText(String.valueOf((int)(Math.sqrt(Integer.parseInt(display.getText())))));
            }else{
                 display.setText(String.valueOf(Math.sqrt(Double.parseDouble(display.getText()))));
            */
       
    }//GEN-LAST:event_sqrtActionPerformed

    private void cubeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cubeActionPerformed
                
          if(decimalClick){
          display.setText(String.valueOf((int)(Math.pow(Integer.parseInt(display.getText()), 3   ))));
            }else{
                 display.setText(String.valueOf(Math.pow(Double.parseDouble(display.getText()), 3 )));
            }
        
        
        
      
    }//GEN-LAST:event_cubeActionPerformed

    private void temp1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_temp1ActionPerformed
       if(displayClick){
        a = Double.parseDouble(display.getText());
        double result = ((a *9/5)+32);
        display.setText(String.valueOf(result) + 'F');
          oneClick =false;
           
                twoClick = false;
                threeClick = false;
                fourClick = false;
                fiveClick = false;
                sixClick = false;
                sevenClick = false;
                eightClick = false;
                nineClick = false;
                decimalClick = true;
       }
    }//GEN-LAST:event_temp1ActionPerformed

    private void temp2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_temp2ActionPerformed
        // TODO add your handling code here:
        if(displayClick){
        a = Double.parseDouble(display.getText());
        double result = ((a  - 32 )*5/9);
        display.setText(String.valueOf(result) + 'C'); 
               oneClick =false;
           
                twoClick = false;
                threeClick = false;
                fourClick = false;
                fiveClick = false;
                sixClick = false;
                sevenClick = false;
                eightClick = false;
                nineClick = false;
                decimalClick = true;
                
        }
    }//GEN-LAST:event_temp2ActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        if(!display.getText().isEmpty()){
       display.setText(display.getText().substring(0, display.getText().length() - 1));
        }
    }//GEN-LAST:event_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calci.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calci.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calci.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calci.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Calci().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JButton clear;
    private javax.swing.JButton cos;
    private javax.swing.JButton cube;
    private javax.swing.JButton decimal;
    private javax.swing.JButton devide;
    private javax.swing.JTextField display;
    private javax.swing.JButton e;
    private javax.swing.JButton eight;
    private javax.swing.JButton equal;
    private javax.swing.JButton five;
    private javax.swing.JButton four;
    private javax.swing.JButton jButton5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JButton log;
    private javax.swing.JButton log2;
    private javax.swing.JButton minus;
    private javax.swing.JButton modulass;
    private javax.swing.JButton multiply;
    private javax.swing.JButton nine;
    private javax.swing.JButton one;
    private javax.swing.JButton plus;
    private javax.swing.JButton plusMinus;
    private javax.swing.JRadioButton scientific;
    private javax.swing.JButton seven;
    private javax.swing.JButton sin;
    private javax.swing.JButton six;
    private javax.swing.JButton sqrt;
    private javax.swing.JButton square;
    private javax.swing.JButton tan;
    private javax.swing.JButton temp1;
    private javax.swing.JButton temp2;
    private javax.swing.JButton three;
    private javax.swing.JButton two;
    private javax.swing.JButton zero;
    // End of variables declaration//GEN-END:variables
}
